language: python
sudo: false
install:
  - pip install tox
script:
  - tox
matrix:
  include:
    - python: 3.4
      env: TOXENV=py34-django19-sqlite
    - python: 3.4
      env: TOXENV=py34-django110-sqlite
    - python: 3.4
      env: TOXENV=py34-django111-sqlite
    - python: 3.6
      env: TOXENV=py36-django19-sqlite
    - python: 3.6
      env: TOXENV=py36-django110-sqlite
    - python: 3.6
      env: TOXENV=py36-django111-sqlite
    - python: 3.6
      env: TOXENV=coverage
    - python: 3.6
      env: TOXENV=doctest
    - python: 3.6
      env: TOXENV=style
